# Generated by Django 4.2.16 on 2024-10-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='multimedia/')),
                ('intervenciones', models.CharField(choices=[('mezcla y masterización', 'mezcla y masterización'), ('mezcla', 'mezcla'), ('masterización', 'masterización'), ('produccion', 'produccion')], max_length=50)),
            ],
        ),
    ]
